name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download DASM
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'dasm-assembler/dasm'
          file: 'dasm-2.20.14.1-linux-x64.tar.gz'
          target: 'dasm/dasm.tar.gz'

      - name: Check file structure
        run: |
          ls -lR

      - name: Decompress DASM
        run: |
          tar --overwrite -xvzf dasm/dasm.tar.gz

      - name: Move DASM to /usr/bin to use with Make
        run: cp ./dasm/dasm /usr/bin

      - name: Checkout zzza repo
        uses: actions/checkout@v4

      - name: Make zzza
        run: |
          ./zzza/zzza/make

      - name: Upload to remove server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: /zzza/zzza/zzza.prg
          remote: ${{ secrets.SERVER_PRG_FOLDER_PATH }}/zzza.prg
          host: caskaydia.com
          username: dylan
          privateKey: ${{ secrets.SERVER_SSH_KEY }}
